env:
  global:
  - IMAGE_NAME=pybot
  - DEPLOY_BRANCHES="master travis"
  - AWS_REGION=us-east-2
  - secure: DcEpdVJ6LoHSLigVem++aZGn0kq74oyPIk/Zifz61NE7nDbustbXahgtMCkiv7dqyd1nqc6E/9S/DZ5dUoWPeeG/VPKkm+Ylk0jZcVLPwSd9S3oICLIZVwL8bG+FwYEY08kGl20rbTMAZT3zIhT0HMmw59UVYr7Lke9vLy2sZKi3nZv7L6miiIBwK3DFuUx3cPTtNXiaszBbUmFLNTNg6ehig2W+FwhHEG2wmd+On5nmArdaXfBDKMXT748aA2y3OG3PTrXdC5OEi0oIaf/8MimIJWzxkoMS8jFoyDSXFOCOzQucv7uAsZHZRACP2HHV5iqOLIo5E6dlONKJFP7TCYqYTzZF8Dz9TUjIMkr+zAeCMrlMzOCVD3qquUoW++s6F71IHGlavqZvMTApyaRCIZanwHk/Tb96/s87bsFPYoGrsInQjfhhPUHTCxZrkBqZg8UegbZJ+HyH+I0bK9WM5mFyeQ7swRFkaQ6MICmqWF0w8JrJUAkOci3Q6NO1+7NBDNT5F3arhHgKMHpw0ry3iuUU1I7Unh8QdzNIgdcAh7TAgI8n0CjBXHf22+ZI0ph4Og7blZ17h9idSj72Ll8a7Rnj3/FgtB7HE1nQMzZfBtiN6txZAhM1ADIDj6NmaIXF+2hkQDnGczGaLqNHlKb14nNfdiWnO8Wf9DKCFZS8iKk=
  - secure: XPvMPMkCIBORXmFSwnSVm6rOF1mHcipzgo9IdbFu87dFFC2mJG/T8UTbEyTLpjpM8WvcSawmpWHtqlhbHXnEj+6ugEongvYsl0wYh/KNU9oS5vw38CvxpvIIg3PyTS39Dp8QtP/y/EaeZPPQiN/soiNGQ0EQ9V/eazjO9Gc9vTvYfPdSc3Q4UjxAqf550L+pkEF6NSh0Lo3ShCr1sai+XCvyvYeTTtwZzufIzq/aNxs+dPUc0FDXdZ5L+J2Ds/yxXAaVcQzSfhdxV1igCcQ6HesndsrrM6DIOTPtzFhpeA3RHaNxrAeh9ZXvYoLkXbyxEmraSRTx0PBjBLNkZNNorOB/ebWj3s1CK5I/3qrZ7WVIq/keDea1Ict9g7moYe8/OLQO0b0/gNqkR/jpepSbfxnEF41DNhJ2xSSE9niuEaUnpDpCibhLCqtXGbRK90dIjnkLHemxL8mrujwm7XDHcTK+GsA5ceBMHk0aQ9WDrKPCQGw8DlQ6EfgnOd/61Dq5vMZW8cC60h8EQNQFQ3KBgEEELpNSltvaf4FYA3Og+Vie/VStjCzDuGohghKiiaGFBWUGtaQGyr4cuwCI88iAU4/LiTz83JAv7+6tD+vsczV8Bdlg360Mquc01E7Vw9Qmtvh1kRWLicA6dUemrUqHO79izqAhhmLhz5dCBZOOGoM=
  - REMOTE_IMAGE_URL=633607774026.dkr.ecr.us-east-2.amazonaws.com/pybot
  - ECS_CLUSTER_MASTER=python-oc-services
  - ECS_SERVICE_MASTER=pybot-svc
  - ECS_CLUSTER_STAGING=python-oc-services
  - ECS_SERVICE_STAGING=pybot-svc-staging
  - PIPENV_CACHE_DIR=~./.cache/pip
sudo: required
os: linux
language: python
cache: pip
python: 3.6
install:
- pip install pipenv
- pipenv install --system --deploy --dev
script:
- pytest
services:
- docker
after_success:
- bash bin/run.sh
